import { jsPDF } from "jspdf";
import type { Severity } from "@/types/scanner";

interface ReportFinding {
  readonly title: string;
  readonly severity: Severity;
  readonly category: string;
  readonly resource: string;
  readonly description: string;
  readonly remediation: string;
}

interface ReportData {
  readonly grade: string;
  readonly gradeLabel: string;
  readonly score: number;
  readonly scannedAt: string;
  readonly targetUrl: string;
  readonly totalFindings: number;
  readonly criticalCount: number;
  readonly highCount: number;
  readonly mediumCount: number;
  readonly lowCount: number;
  readonly findings: readonly ReportFinding[];
}

const SEVERITY_ORDER: readonly Severity[] = [
  "critical",
  "high",
  "medium",
  "low",
];

const SEVERITY_COLORS: Record<Severity, readonly [number, number, number]> = {
  critical: [220, 38, 38],
  high: [234, 88, 12],
  medium: [217, 119, 6],
  low: [37, 99, 235],
};

const GRADE_LABELS: Record<string, string> = {
  A: "Excellent",
  B: "Good",
  C: "Needs Improvement",
  D: "Poor",
  F: "Critical",
};

const GRADE_SCORES: Record<string, number> = {
  A: 100,
  B: 80,
  C: 60,
  D: 40,
  F: 20,
};

export function generateScanReportPdf(
  data: ReportData,
  isPro: boolean,
): ArrayBuffer {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 50;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  function addFooter() {
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text(
      "Generated by SupaScanner | supascanner.com",
      pageWidth / 2,
      pageHeight - 25,
      { align: "center" },
    );
    doc.setDrawColor(230, 230, 230);
    doc.line(margin, pageHeight - 40, pageWidth - margin, pageHeight - 40);
  }

  function checkPageBreak(requiredSpace: number) {
    if (y + requiredSpace > pageHeight - 60) {
      addFooter();
      doc.addPage();
      y = margin;
    }
  }

  function wrapText(
    text: string,
    maxWidth: number,
    fontSize: number,
  ): readonly string[] {
    doc.setFontSize(fontSize);
    return doc.splitTextToSize(text, maxWidth) as string[];
  }

  // -- Header --
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23); // sand-900
  doc.text("SupaScanner Security Report", margin, y);
  y += 12;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 113, 108); // sand-400
  const scanDate = new Date(data.scannedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  doc.text(`Scanned: ${scanDate}`, margin, y + 16);
  doc.text(`Target: ${data.targetUrl}`, margin, y + 30);
  y += 48;

  doc.setDrawColor(232, 229, 224); // sand-200
  doc.line(margin, y, pageWidth - margin, y);
  y += 24;

  // -- Grade Badge --
  const gradeBoxX = margin;
  const gradeBoxW = 100;
  const gradeBoxH = 80;

  doc.setFillColor(250, 249, 247); // sand-50
  doc.setDrawColor(232, 229, 224);
  doc.roundedRect(gradeBoxX, y, gradeBoxW, gradeBoxH, 8, 8, "FD");

  doc.setFontSize(42);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text(data.grade, gradeBoxX + gradeBoxW / 2, y + 48, {
    align: "center",
  });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 113, 108);
  const label = GRADE_LABELS[data.grade] ?? "";
  doc.text(label, gradeBoxX + gradeBoxW / 2, y + 66, { align: "center" });

  // -- Severity Summary --
  const statsX = gradeBoxX + gradeBoxW + 30;
  const statColWidth = (contentWidth - gradeBoxW - 30) / 4;

  const stats = [
    { label: "Critical", count: data.criticalCount, severity: "critical" },
    { label: "High", count: data.highCount, severity: "high" },
    { label: "Medium", count: data.mediumCount, severity: "medium" },
    { label: "Low", count: data.lowCount, severity: "low" },
  ] as const;

  for (let i = 0; i < stats.length; i++) {
    const stat = stats[i];
    const sx = statsX + i * statColWidth;

    doc.setFontSize(26);
    doc.setFont("helvetica", "bold");
    const [r, g, b] = SEVERITY_COLORS[stat.severity];
    doc.setTextColor(r, g, b);
    doc.text(String(stat.count), sx + statColWidth / 2, y + 40, {
      align: "center",
    });

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 113, 108);
    doc.text(stat.label, sx + statColWidth / 2, y + 56, {
      align: "center",
    });
  }

  y += gradeBoxH + 16;

  doc.setFontSize(9);
  doc.setTextColor(160, 160, 160);
  doc.text(
    `${data.totalFindings} total finding${data.totalFindings !== 1 ? "s" : ""} | Security Score: ${GRADE_SCORES[data.grade] ?? 0}/100`,
    margin,
    y,
  );
  y += 24;

  doc.setDrawColor(232, 229, 224);
  doc.line(margin, y, pageWidth - margin, y);
  y += 20;

  // -- Free tier upgrade notice --
  if (!isPro) {
    checkPageBreak(80);

    doc.setFillColor(250, 249, 247);
    doc.setDrawColor(232, 229, 224);
    doc.roundedRect(margin, y, contentWidth, 60, 6, 6, "FD");

    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(28, 25, 23);
    doc.text("Upgrade to Pro for Full Report", margin + 16, y + 24);

    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 113, 108);
    doc.text(
      "Get detailed findings with remediation guidance, SQL fix snippets, and step-by-step instructions.",
      margin + 16,
      y + 42,
    );

    y += 76;
    addFooter();
    return doc.output("arraybuffer");
  }

  // -- Findings Detail (Pro only) --
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text("Findings", margin, y);
  y += 20;

  for (const severity of SEVERITY_ORDER) {
    const severityFindings = data.findings.filter(
      (f) => f.severity === severity,
    );
    if (severityFindings.length === 0) continue;

    checkPageBreak(60);

    // Severity section header
    const [sr, sg, sb] = SEVERITY_COLORS[severity];
    doc.setFillColor(sr, sg, sb);
    doc.roundedRect(margin, y, 8, 18, 2, 2, "F");

    doc.setFontSize(13);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(28, 25, 23);
    const headerText = `${severity.charAt(0).toUpperCase() + severity.slice(1)} (${severityFindings.length})`;
    doc.text(headerText, margin + 16, y + 13);
    y += 30;

    for (const finding of severityFindings) {
      checkPageBreak(100);

      // Finding card background
      doc.setFillColor(252, 252, 251);
      doc.setDrawColor(232, 229, 224);

      // Title
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(28, 25, 23);
      const titleLines = wrapText(finding.title, contentWidth - 20, 11);
      for (const line of titleLines) {
        checkPageBreak(20);
        doc.text(line, margin + 10, y);
        y += 14;
      }

      // Category + resource
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(160, 160, 160);
      doc.text(
        `${finding.category.toUpperCase()} | ${finding.resource}`,
        margin + 10,
        y,
      );
      y += 14;

      // Description
      doc.setFontSize(9);
      doc.setTextColor(68, 64, 60); // sand-700
      const descLines = wrapText(finding.description, contentWidth - 20, 9);
      for (const line of descLines) {
        checkPageBreak(14);
        doc.text(line, margin + 10, y);
        y += 12;
      }
      y += 4;

      // Remediation
      checkPageBreak(30);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(28, 25, 23);
      doc.text("Remediation:", margin + 10, y);
      y += 12;

      doc.setFont("helvetica", "normal");
      doc.setTextColor(68, 64, 60);
      const remLines = wrapText(finding.remediation, contentWidth - 20, 9);
      for (const line of remLines) {
        checkPageBreak(14);
        doc.text(line, margin + 10, y);
        y += 12;
      }

      y += 12;

      // Separator between findings
      doc.setDrawColor(240, 240, 240);
      doc.line(margin + 10, y, pageWidth - margin - 10, y);
      y += 12;
    }

    y += 8;
  }

  addFooter();
  return doc.output("arraybuffer");
}

export function buildReportData(
  scanJob: {
    readonly grade: string;
    readonly supabase_url: string;
    readonly total_findings: number;
    readonly created_at: string;
  },
  findings: readonly {
    readonly title: string;
    readonly severity: Severity;
    readonly category: string;
    readonly resource: string;
    readonly description: string;
    readonly remediation: string;
  }[],
): ReportData {
  return {
    grade: scanJob.grade,
    gradeLabel: GRADE_LABELS[scanJob.grade] ?? "",
    score: GRADE_SCORES[scanJob.grade] ?? 0,
    scannedAt: scanJob.created_at,
    targetUrl: scanJob.supabase_url,
    totalFindings: scanJob.total_findings,
    criticalCount: findings.filter((f) => f.severity === "critical").length,
    highCount: findings.filter((f) => f.severity === "high").length,
    mediumCount: findings.filter((f) => f.severity === "medium").length,
    lowCount: findings.filter((f) => f.severity === "low").length,
    findings,
  };
}
