import { jsPDF } from "jspdf";
import type { ComplianceCheckResult } from "./frameworks";
import { getFrameworkSummary } from "./frameworks";
import type { Severity } from "@/types/scanner";

interface ExecutiveSummaryData {
  readonly targetUrl: string;
  readonly scannedAt: string;
  readonly grade: string;
  readonly totalFindings: number;
  readonly criticalCount: number;
  readonly highCount: number;
  readonly mediumCount: number;
  readonly lowCount: number;
  readonly soc2Results: readonly ComplianceCheckResult[];
  readonly hipaaResults: readonly ComplianceCheckResult[];
}

const SEVERITY_COLORS: Record<Severity, readonly [number, number, number]> = {
  critical: [220, 38, 38],
  high: [234, 88, 12],
  medium: [217, 119, 6],
  low: [37, 99, 235],
};

const GRADE_LABELS: Record<string, string> = {
  A: "Excellent",
  B: "Good",
  C: "Needs Improvement",
  D: "Poor",
  F: "Critical",
};

export function generateExecutiveSummaryPdf(
  data: ExecutiveSummaryData,
): ArrayBuffer {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 50;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const soc2Summary = getFrameworkSummary(data.soc2Results);
  const hipaaSummary = getFrameworkSummary(data.hipaaResults);

  function addFooter() {
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text(
      "Generated by SupaScanner | Compliance Executive Summary | supascanner.com",
      pageWidth / 2,
      pageHeight - 25,
      { align: "center" },
    );
    doc.setDrawColor(230, 230, 230);
    doc.line(margin, pageHeight - 40, pageWidth - margin, pageHeight - 40);
  }

  function checkPageBreak(requiredSpace: number) {
    if (y + requiredSpace > pageHeight - 60) {
      addFooter();
      doc.addPage();
      y = margin;
    }
  }

  function wrapText(
    text: string,
    maxWidth: number,
    fontSize: number,
  ): readonly string[] {
    doc.setFontSize(fontSize);
    return doc.splitTextToSize(text, maxWidth) as string[];
  }

  // -- Header --
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text("Compliance Executive Summary", margin, y);
  y += 12;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 113, 108);
  const scanDate = new Date(data.scannedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  doc.text(`Report Date: ${scanDate}`, margin, y + 16);
  doc.text(`Target System: ${data.targetUrl}`, margin, y + 30);
  y += 48;

  doc.setDrawColor(232, 229, 224);
  doc.line(margin, y, pageWidth - margin, y);
  y += 24;

  // -- Security Posture Overview --
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text("Security Posture Overview", margin, y);
  y += 24;

  // Grade + severity summary row
  const gradeBoxW = 100;
  const gradeBoxH = 80;

  doc.setFillColor(250, 249, 247);
  doc.setDrawColor(232, 229, 224);
  doc.roundedRect(margin, y, gradeBoxW, gradeBoxH, 8, 8, "FD");
  doc.setFontSize(42);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text(data.grade, margin + gradeBoxW / 2, y + 48, { align: "center" });
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 113, 108);
  doc.text(GRADE_LABELS[data.grade] ?? "", margin + gradeBoxW / 2, y + 64, {
    align: "center",
  });

  const severityStats = [
    { label: "Critical", count: data.criticalCount, severity: "critical" as Severity },
    { label: "High", count: data.highCount, severity: "high" as Severity },
    { label: "Medium", count: data.mediumCount, severity: "medium" as Severity },
    { label: "Low", count: data.lowCount, severity: "low" as Severity },
  ];

  const sevStatsX = margin + gradeBoxW + 30;
  const sevStatW = (contentWidth - gradeBoxW - 30) / 4;

  for (let i = 0; i < severityStats.length; i++) {
    const stat = severityStats[i];
    const sx = sevStatsX + i * sevStatW;
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    const [r, g, b] = SEVERITY_COLORS[stat.severity];
    doc.setTextColor(r, g, b);
    doc.text(String(stat.count), sx + sevStatW / 2, y + 40, {
      align: "center",
    });
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 113, 108);
    doc.text(stat.label, sx + sevStatW / 2, y + 56, { align: "center" });
  }

  y += gradeBoxH + 10;
  doc.setFontSize(9);
  doc.setTextColor(160, 160, 160);
  doc.text(
    `${data.totalFindings} total finding${data.totalFindings !== 1 ? "s" : ""} across all scanner modules`,
    margin,
    y,
  );
  y += 24;

  doc.setDrawColor(232, 229, 224);
  doc.line(margin, y, pageWidth - margin, y);
  y += 24;

  // -- Framework Comparison --
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text("Compliance Framework Readiness", margin, y);
  y += 24;

  const frameworkBoxW = (contentWidth - 20) / 2;
  const frameworkBoxH = 120;

  // SOC 2 box
  drawFrameworkBox(doc, margin, y, frameworkBoxW, frameworkBoxH, {
    title: "SOC 2 Type II",
    readiness: soc2Summary.readinessPercent,
    passed: soc2Summary.passed,
    failed: soc2Summary.failed,
    warnings: soc2Summary.warnings,
    total: soc2Summary.total,
  });

  // HIPAA box
  drawFrameworkBox(
    doc,
    margin + frameworkBoxW + 20,
    y,
    frameworkBoxW,
    frameworkBoxH,
    {
      title: "HIPAA Security Rule",
      readiness: hipaaSummary.readinessPercent,
      passed: hipaaSummary.passed,
      failed: hipaaSummary.failed,
      warnings: hipaaSummary.warnings,
      total: hipaaSummary.total,
    },
  );

  y += frameworkBoxH + 24;

  doc.setDrawColor(232, 229, 224);
  doc.line(margin, y, pageWidth - margin, y);
  y += 24;

  // -- Critical Findings --
  checkPageBreak(80);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text("Critical & High Priority Findings", margin, y);
  y += 20;

  const allFindings = [
    ...data.soc2Results.flatMap((r) => r.findings),
    ...data.hipaaResults.flatMap((r) => r.findings),
  ];

  // Deduplicate by title
  const seen = new Set<string>();
  const uniqueFindings = allFindings.filter((f) => {
    if (seen.has(f.title)) return false;
    seen.add(f.title);
    return f.severity === "critical" || f.severity === "high";
  });

  if (uniqueFindings.length === 0) {
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(22, 163, 74);
    doc.text("No critical or high priority findings detected.", margin + 10, y);
    y += 20;
  } else {
    for (const finding of uniqueFindings) {
      checkPageBreak(50);

      const [fr, fg, fb] = SEVERITY_COLORS[finding.severity];

      doc.setFillColor(fr, fg, fb);
      doc.roundedRect(margin, y, 6, 14, 2, 2, "F");

      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(28, 25, 23);
      const titleLines = wrapText(finding.title, contentWidth - 20, 10);
      doc.text(titleLines[0], margin + 14, y + 10);
      y += 18;

      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(120, 113, 108);
      doc.text(
        `${finding.category.toUpperCase()} | ${finding.resource}`,
        margin + 14,
        y,
      );
      y += 12;

      doc.setTextColor(68, 64, 60);
      const remLines = wrapText(finding.remediation, contentWidth - 20, 8);
      for (const line of remLines.slice(0, 2)) {
        checkPageBreak(12);
        doc.text(line, margin + 14, y);
        y += 10;
      }

      y += 8;
    }
  }

  y += 12;
  checkPageBreak(80);
  doc.setDrawColor(232, 229, 224);
  doc.line(margin, y, pageWidth - margin, y);
  y += 24;

  // -- Recommendations --
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text("Recommendations", margin, y);
  y += 20;

  const recommendations = buildRecommendations(data, soc2Summary, hipaaSummary);
  for (const rec of recommendations) {
    checkPageBreak(30);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(28, 25, 23);
    const recLines = wrapText(`${rec.priority}. ${rec.text}`, contentWidth - 10, 9);
    doc.text(recLines[0], margin + 10, y);
    y += 12;

    if (rec.detail) {
      doc.setFont("helvetica", "normal");
      doc.setTextColor(120, 113, 108);
      doc.setFontSize(8);
      const detailLines = wrapText(rec.detail, contentWidth - 20, 8);
      for (const line of detailLines.slice(0, 2)) {
        checkPageBreak(12);
        doc.text(line, margin + 16, y);
        y += 10;
      }
    }
    y += 6;
  }

  addFooter();
  return doc.output("arraybuffer");
}

function drawFrameworkBox(
  doc: jsPDF,
  x: number,
  y: number,
  w: number,
  h: number,
  data: {
    readonly title: string;
    readonly readiness: number;
    readonly passed: number;
    readonly failed: number;
    readonly warnings: number;
    readonly total: number;
  },
) {
  doc.setFillColor(250, 249, 247);
  doc.setDrawColor(232, 229, 224);
  doc.roundedRect(x, y, w, h, 6, 6, "FD");

  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text(data.title, x + 12, y + 20);

  // Readiness percentage
  const readinessColor =
    data.readiness >= 80
      ? [22, 163, 74]
      : data.readiness >= 50
        ? [217, 119, 6]
        : [220, 38, 38];

  doc.setFontSize(28);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(readinessColor[0], readinessColor[1], readinessColor[2]);
  doc.text(`${data.readiness}%`, x + 12, y + 56);

  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 113, 108);
  doc.text("readiness", x + 12, y + 68);

  // Stats
  doc.setFontSize(8);
  const statsY = y + 90;
  doc.setTextColor(22, 163, 74);
  doc.text(`${data.passed} passing`, x + 12, statsY);
  doc.setTextColor(220, 38, 38);
  doc.text(`${data.failed} failing`, x + 80, statsY);
  doc.setTextColor(217, 119, 6);
  doc.text(`${data.warnings} warnings`, x + 140, statsY);

  // Progress bar
  const barY = y + 100;
  const barW = w - 24;
  const barH = 6;
  doc.setFillColor(232, 229, 224);
  doc.roundedRect(x + 12, barY, barW, barH, 3, 3, "F");

  const filledW = (data.readiness / 100) * barW;
  if (filledW > 0) {
    doc.setFillColor(readinessColor[0], readinessColor[1], readinessColor[2]);
    doc.roundedRect(x + 12, barY, filledW, barH, 3, 3, "F");
  }
}

function buildRecommendations(
  data: ExecutiveSummaryData,
  soc2Summary: ReturnType<typeof getFrameworkSummary>,
  hipaaSummary: ReturnType<typeof getFrameworkSummary>,
): readonly { readonly priority: number; readonly text: string; readonly detail: string }[] {
  const recs: { priority: number; text: string; detail: string }[] = [];
  let priority = 1;

  if (data.criticalCount > 0) {
    recs.push({
      priority: priority++,
      text: `Resolve ${data.criticalCount} critical finding${data.criticalCount !== 1 ? "s" : ""} immediately`,
      detail:
        "Critical findings indicate active security vulnerabilities that could lead to data exposure or unauthorized access.",
    });
  }

  if (data.highCount > 0) {
    recs.push({
      priority: priority++,
      text: `Address ${data.highCount} high-severity finding${data.highCount !== 1 ? "s" : ""} within 30 days`,
      detail:
        "High-severity findings represent significant risks that should be prioritized in the next remediation cycle.",
    });
  }

  if (soc2Summary.failed > 0) {
    recs.push({
      priority: priority++,
      text: `Remediate ${soc2Summary.failed} failing SOC 2 control${soc2Summary.failed !== 1 ? "s" : ""} before audit engagement`,
      detail:
        "Failing controls will likely result in audit exceptions. Address these before scheduling a SOC 2 Type I or II audit.",
    });
  }

  if (hipaaSummary.failed > 0) {
    recs.push({
      priority: priority++,
      text: `Address ${hipaaSummary.failed} non-compliant HIPAA control${hipaaSummary.failed !== 1 ? "s" : ""} if processing ePHI`,
      detail:
        "Non-compliant HIPAA controls must be resolved before storing or processing electronic Protected Health Information.",
    });
  }

  if (soc2Summary.warnings > 0 || hipaaSummary.warnings > 0) {
    recs.push({
      priority: priority++,
      text: "Review and address warning-level compliance items",
      detail:
        "Warning items indicate potential gaps that should be evaluated for risk acceptance or remediation.",
    });
  }

  recs.push({
    priority: priority++,
    text: "Schedule regular compliance scans",
    detail:
      "Run compliance assessments weekly or after significant infrastructure changes to maintain continuous readiness.",
  });

  return recs;
}
