import { jsPDF } from "jspdf";
import type { ComplianceCheckResult } from "./frameworks";
import { getFrameworkSummary } from "./frameworks";

interface Soc2ReportData {
  readonly targetUrl: string;
  readonly scannedAt: string;
  readonly grade: string;
  readonly results: readonly ComplianceCheckResult[];
}

const STATUS_COLORS: Record<string, readonly [number, number, number]> = {
  pass: [22, 163, 74],
  fail: [220, 38, 38],
  warning: [217, 119, 6],
  not_assessed: [160, 160, 160],
};

const STATUS_LABELS: Record<string, string> = {
  pass: "PASS",
  fail: "FAIL",
  warning: "WARNING",
  not_assessed: "N/A",
};

export function generateSoc2ReportPdf(data: Soc2ReportData): ArrayBuffer {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 50;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const summary = getFrameworkSummary(data.results);

  function addFooter() {
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text(
      "Generated by SupaScanner | SOC 2 Readiness Assessment | supascanner.com",
      pageWidth / 2,
      pageHeight - 25,
      { align: "center" },
    );
    doc.setDrawColor(230, 230, 230);
    doc.line(margin, pageHeight - 40, pageWidth - margin, pageHeight - 40);
  }

  function checkPageBreak(requiredSpace: number) {
    if (y + requiredSpace > pageHeight - 60) {
      addFooter();
      doc.addPage();
      y = margin;
    }
  }

  function wrapText(
    text: string,
    maxWidth: number,
    fontSize: number,
  ): readonly string[] {
    doc.setFontSize(fontSize);
    return doc.splitTextToSize(text, maxWidth) as string[];
  }

  // -- Header --
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text("SOC 2 Readiness Assessment", margin, y);
  y += 12;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 113, 108);
  const scanDate = new Date(data.scannedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  doc.text(`Scanned: ${scanDate}`, margin, y + 16);
  doc.text(`Target: ${data.targetUrl}`, margin, y + 30);
  doc.text(`Security Grade: ${data.grade}`, margin, y + 44);
  y += 60;

  doc.setDrawColor(232, 229, 224);
  doc.line(margin, y, pageWidth - margin, y);
  y += 20;

  // -- Disclaimer --
  doc.setFillColor(255, 251, 235);
  doc.setDrawColor(253, 230, 138);
  doc.roundedRect(margin, y, contentWidth, 48, 4, 4, "FD");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(146, 64, 14);
  doc.text("DISCLAIMER", margin + 12, y + 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  const disclaimerLines = wrapText(
    "This is an automated readiness assessment based on scan findings, not a formal SOC 2 audit. A qualified CPA firm must perform the official Type I or Type II audit. Use this report to identify gaps before engaging auditors.",
    contentWidth - 24,
    7,
  );
  for (let i = 0; i < disclaimerLines.length; i++) {
    doc.text(disclaimerLines[i], margin + 12, y + 26 + i * 10);
  }
  y += 60;

  // -- Readiness Summary --
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text("Readiness Summary", margin, y);
  y += 24;

  const readinessBoxW = 120;
  const readinessBoxH = 70;

  doc.setFillColor(250, 249, 247);
  doc.setDrawColor(232, 229, 224);
  doc.roundedRect(margin, y, readinessBoxW, readinessBoxH, 8, 8, "FD");
  doc.setFontSize(32);
  doc.setFont("helvetica", "bold");
  const readinessColor =
    summary.readinessPercent >= 80
      ? [22, 163, 74]
      : summary.readinessPercent >= 50
        ? [217, 119, 6]
        : [220, 38, 38];
  doc.setTextColor(readinessColor[0], readinessColor[1], readinessColor[2]);
  doc.text(`${summary.readinessPercent}%`, margin + readinessBoxW / 2, y + 40, {
    align: "center",
  });
  doc.setFontSize(9);
  doc.setTextColor(120, 113, 108);
  doc.text("Readiness", margin + readinessBoxW / 2, y + 56, {
    align: "center",
  });

  // Stats next to readiness
  const statsX = margin + readinessBoxW + 30;
  const statW = (contentWidth - readinessBoxW - 30) / 3;

  const stats = [
    { label: "Controls Passing", count: summary.passed, color: STATUS_COLORS.pass },
    { label: "Controls Failing", count: summary.failed, color: STATUS_COLORS.fail },
    { label: "Warnings", count: summary.warnings, color: STATUS_COLORS.warning },
  ] as const;

  for (let i = 0; i < stats.length; i++) {
    const stat = stats[i];
    const sx = statsX + i * statW;
    doc.setFontSize(24);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(stat.color[0], stat.color[1], stat.color[2]);
    doc.text(String(stat.count), sx + statW / 2, y + 40, { align: "center" });
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 113, 108);
    doc.text(stat.label, sx + statW / 2, y + 56, { align: "center" });
  }

  y += readinessBoxH + 24;

  doc.setDrawColor(232, 229, 224);
  doc.line(margin, y, pageWidth - margin, y);
  y += 20;

  // -- Control Details --
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text("Trust Service Criteria Assessment", margin, y);
  y += 24;

  for (const result of data.results) {
    checkPageBreak(80);

    const [sr, sg, sb] = STATUS_COLORS[result.status];

    // Status badge
    doc.setFillColor(sr, sg, sb);
    doc.roundedRect(margin, y, 50, 16, 3, 3, "F");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(255, 255, 255);
    doc.text(STATUS_LABELS[result.status], margin + 25, y + 11, {
      align: "center",
    });

    // Control ID and name
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(28, 25, 23);
    doc.text(
      `${result.control.id} - ${result.control.name}`,
      margin + 58,
      y + 12,
    );
    y += 22;

    // Control description
    doc.setFontSize(8);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 113, 108);
    const descLines = wrapText(result.control.description, contentWidth - 10, 8);
    for (const line of descLines) {
      checkPageBreak(12);
      doc.text(line, margin + 10, y);
      y += 10;
    }
    y += 4;

    // Related findings
    if (result.findings.length > 0) {
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(68, 64, 60);
      doc.text(
        `Related findings (${result.findings.length}):`,
        margin + 10,
        y,
      );
      y += 12;

      for (const finding of result.findings) {
        checkPageBreak(30);

        const [fr, fg, fb] =
          finding.severity === "critical"
            ? [220, 38, 38]
            : finding.severity === "high"
              ? [234, 88, 12]
              : finding.severity === "medium"
                ? [217, 119, 6]
                : [37, 99, 235];

        doc.setFontSize(7);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(fr, fg, fb);
        doc.text(finding.severity.toUpperCase(), margin + 16, y);
        doc.setTextColor(68, 64, 60);
        doc.setFont("helvetica", "normal");
        const titleLines = wrapText(finding.title, contentWidth - 80, 7);
        doc.text(titleLines[0], margin + 60, y);
        y += 10;

        doc.setFontSize(7);
        doc.setTextColor(120, 113, 108);
        const remLines = wrapText(
          `Remediation: ${finding.remediation}`,
          contentWidth - 30,
          7,
        );
        for (const line of remLines.slice(0, 2)) {
          checkPageBreak(10);
          doc.text(line, margin + 20, y);
          y += 9;
        }
        y += 4;
      }
    }

    y += 8;

    // Separator
    doc.setDrawColor(240, 240, 240);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;
  }

  addFooter();
  return doc.output("arraybuffer");
}
