import { jsPDF } from "jspdf";
import type { ComplianceCheckResult } from "./frameworks";
import { getFrameworkSummary } from "./frameworks";

interface HipaaReportData {
  readonly targetUrl: string;
  readonly scannedAt: string;
  readonly grade: string;
  readonly results: readonly ComplianceCheckResult[];
}

const STATUS_COLORS: Record<string, readonly [number, number, number]> = {
  pass: [22, 163, 74],
  fail: [220, 38, 38],
  warning: [217, 119, 6],
  not_assessed: [160, 160, 160],
};

const STATUS_LABELS: Record<string, string> = {
  pass: "COMPLIANT",
  fail: "NON-COMPLIANT",
  warning: "NEEDS REVIEW",
  not_assessed: "N/A",
};

export function generateHipaaReportPdf(data: HipaaReportData): ArrayBuffer {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 50;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const summary = getFrameworkSummary(data.results);

  function addFooter() {
    doc.setFontSize(8);
    doc.setTextColor(160, 160, 160);
    doc.text(
      "Generated by SupaScanner | HIPAA Security Checklist | supascanner.com",
      pageWidth / 2,
      pageHeight - 25,
      { align: "center" },
    );
    doc.setDrawColor(230, 230, 230);
    doc.line(margin, pageHeight - 40, pageWidth - margin, pageHeight - 40);
  }

  function checkPageBreak(requiredSpace: number) {
    if (y + requiredSpace > pageHeight - 60) {
      addFooter();
      doc.addPage();
      y = margin;
    }
  }

  function wrapText(
    text: string,
    maxWidth: number,
    fontSize: number,
  ): readonly string[] {
    doc.setFontSize(fontSize);
    return doc.splitTextToSize(text, maxWidth) as string[];
  }

  // -- Header --
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text("HIPAA Security Rule Checklist", margin, y);
  y += 12;

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 113, 108);
  const scanDate = new Date(data.scannedAt).toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
    hour: "2-digit",
    minute: "2-digit",
  });
  doc.text(`Assessment Date: ${scanDate}`, margin, y + 16);
  doc.text(`System: ${data.targetUrl}`, margin, y + 30);
  doc.text(`Security Grade: ${data.grade}`, margin, y + 44);
  y += 60;

  doc.setDrawColor(232, 229, 224);
  doc.line(margin, y, pageWidth - margin, y);
  y += 20;

  // -- Disclaimer --
  doc.setFillColor(254, 242, 242);
  doc.setDrawColor(252, 165, 165);
  doc.roundedRect(margin, y, contentWidth, 56, 4, 4, "FD");
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(153, 27, 27);
  doc.text("IMPORTANT NOTICE", margin + 12, y + 14);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(7);
  const disclaimerLines = wrapText(
    "This automated checklist evaluates technical safeguards detectable through external scanning of your Supabase configuration. It does not constitute a complete HIPAA compliance assessment. Administrative safeguards, physical safeguards, organizational requirements, and policies/procedures must be assessed separately. Consult a qualified HIPAA compliance officer for a full evaluation.",
    contentWidth - 24,
    7,
  );
  for (let i = 0; i < disclaimerLines.length; i++) {
    doc.text(disclaimerLines[i], margin + 12, y + 26 + i * 10);
  }
  y += 68;

  // -- Compliance Summary --
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text("Technical Safeguards Summary", margin, y);
  y += 24;

  const statBoxH = 60;
  const statBoxW = contentWidth / 4 - 8;

  const summaryStats = [
    {
      label: "Compliant",
      count: summary.passed,
      color: STATUS_COLORS.pass,
    },
    {
      label: "Non-Compliant",
      count: summary.failed,
      color: STATUS_COLORS.fail,
    },
    {
      label: "Needs Review",
      count: summary.warnings,
      color: STATUS_COLORS.warning,
    },
    {
      label: "Total Controls",
      count: summary.total,
      color: [28, 25, 23] as readonly [number, number, number],
    },
  ] as const;

  for (let i = 0; i < summaryStats.length; i++) {
    const stat = summaryStats[i];
    const sx = margin + i * (statBoxW + 10);

    doc.setFillColor(250, 249, 247);
    doc.setDrawColor(232, 229, 224);
    doc.roundedRect(sx, y, statBoxW, statBoxH, 4, 4, "FD");

    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(stat.color[0], stat.color[1], stat.color[2]);
    doc.text(String(stat.count), sx + statBoxW / 2, y + 30, {
      align: "center",
    });

    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 113, 108);
    doc.text(stat.label, sx + statBoxW / 2, y + 46, { align: "center" });
  }

  y += statBoxH + 24;

  doc.setDrawColor(232, 229, 224);
  doc.line(margin, y, pageWidth - margin, y);
  y += 20;

  // -- Checklist --
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(28, 25, 23);
  doc.text("Security Rule Checklist", margin, y);
  y += 24;

  for (const result of data.results) {
    checkPageBreak(70);

    // Checklist row
    const rowHeight = 20;

    // Status indicator
    const [sr, sg, sb] = STATUS_COLORS[result.status];
    const checkboxSize = 12;
    doc.setDrawColor(sr, sg, sb);
    doc.setFillColor(sr, sg, sb);

    if (result.status === "pass") {
      doc.roundedRect(margin, y, checkboxSize, checkboxSize, 2, 2, "FD");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text("✓", margin + 2.5, y + 10);
    } else if (result.status === "fail") {
      doc.roundedRect(margin, y, checkboxSize, checkboxSize, 2, 2, "FD");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(9);
      doc.setFont("helvetica", "bold");
      doc.text("✗", margin + 2.5, y + 10);
    } else {
      doc.roundedRect(margin, y, checkboxSize, checkboxSize, 2, 2, "D");
      doc.setTextColor(sr, sg, sb);
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.text("!", margin + 3.5, y + 10);
    }

    // Section reference and name
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(28, 25, 23);
    doc.text(`${result.control.id}`, margin + 20, y + 10);

    doc.setFont("helvetica", "normal");
    doc.setTextColor(68, 64, 60);
    doc.text(`${result.control.name}`, margin + 110, y + 10);

    // Status text
    doc.setFontSize(7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(sr, sg, sb);
    doc.text(
      STATUS_LABELS[result.status],
      pageWidth - margin,
      y + 10,
      { align: "right" },
    );

    y += rowHeight + 2;

    // Requirement description
    doc.setFontSize(7);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(120, 113, 108);
    const descLines = wrapText(result.control.description, contentWidth - 30, 7);
    for (const line of descLines) {
      checkPageBreak(10);
      doc.text(line, margin + 20, y);
      y += 9;
    }
    y += 4;

    // Findings that impact this control
    if (result.findings.length > 0) {
      doc.setFontSize(7);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(220, 38, 38);
      doc.text("Issues detected:", margin + 20, y);
      y += 10;

      for (const finding of result.findings) {
        checkPageBreak(20);
        doc.setFontSize(7);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(68, 64, 60);
        const findingLines = wrapText(
          `- [${finding.severity.toUpperCase()}] ${finding.title}`,
          contentWidth - 40,
          7,
        );
        for (const line of findingLines) {
          checkPageBreak(10);
          doc.text(line, margin + 24, y);
          y += 9;
        }
      }
      y += 2;

      // Remediation summary
      const uniqueRemediations = [
        ...new Set(result.findings.map((f) => f.remediation)),
      ];
      if (uniqueRemediations.length > 0) {
        checkPageBreak(20);
        doc.setFontSize(7);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(22, 163, 74);
        doc.text("Required actions:", margin + 20, y);
        y += 10;

        for (const rem of uniqueRemediations.slice(0, 3)) {
          checkPageBreak(16);
          doc.setFont("helvetica", "normal");
          doc.setTextColor(68, 64, 60);
          const remLines = wrapText(`- ${rem}`, contentWidth - 40, 7);
          for (const line of remLines.slice(0, 2)) {
            checkPageBreak(10);
            doc.text(line, margin + 24, y);
            y += 9;
          }
        }
      }
    }

    y += 8;
    doc.setDrawColor(240, 240, 240);
    doc.line(margin + 20, y, pageWidth - margin, y);
    y += 8;
  }

  addFooter();
  return doc.output("arraybuffer");
}
